Force stable-repo-url for Helm <2.16.x versions
If using any Helm version previous to 2.17, the default stable repo url https://kubernetes-charts.storage.googleapis.com/index.yaml is not available any longer, so the `helm init` command fails.
```
Running: helm init --client-only
Creating /builder/home/.helm/repository/repositories.yaml 
Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com 
Error: error initializing: Looks like "https://kubernetes-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: Failed to fetch https://kubernetes-charts.storage.googleapis.com/index.yaml : 403 Forbidden
```

This commit forces the stable repo url to `https://charts.helm.sh/stable`.